const DATE_FORMAT = {
  MONTH_AND_YEAR: 'MMMM YYYY',
  ONE_DIGIT_DATE: 'D',
  TWO_DIGIT_DATE: 'DD',
  TWO_LETTER_DAY: 'dd',
  DAY_OF_WEEK: 'ddd',
  FULL_DATE: 'DD-MM-YY',
  DAY_AND_WEEK: 'dddd, MMMM DD',
}

export { DATE_FORMAT }
